function [rnames, values] = Get_stim_param_values(p, r, s)
global n
global ParamsSave

%% common parameters
values = {
    r.rect;...
    r.sampf;...
    s.pattern;...
    n
    };
%% stimulus specific parameters
pos = [num2str(s.divnum),'x',num2str(s.divnum),'=>'];
switch s.pattern
    case {'Uni', 'Size_rand'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Freq(Hz)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size(deg)';...
            'Position';...
            'Stim_lumi';...
            'BG_lumi';...
            'Stim_Color';...
            'Duration(sec)';...
            'Corrected Stim ON(sec)';...
            'Corrected Stim OFF(sec)';...
            };
        
        if n <= r.prestim
            pre_val={'NA';'NA';'NA';'NA';'NA';'NA';'NA';'NA'};
            values = [values; pre_val];
        else
            s1n = p{1,n}.stim1;
            specific_val={s1n.size_deg;...
                [pos,num2str(s1n.center_position)];...
                s1n.lumi; num2str(s.bgcol); s1n.color(1);...
                s1n.Off_time - s1n.On_time;...
                ParamsSave{1,n}.stim1.corON;...
                ParamsSave{1,n}.stim1.corOFF;...
                };
            values = [values; specific_val];
        end
        
    case {'1P_Conc'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size(deg)';...
            'Center';...
            'Position (dist * angle)';...
            'Stim_lumi';...
            'BG_lumi';...
            'Stim_Color';...
            'Duration(sec)';...
            'Corrected Stim ON(sec)';...
            'Corrected Stim OFF(sec)'
            };
    case {'2P_Conc'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size1(deg)';...
            'Size2(deg)';...
            'Stim1 Position';...
            'Stim2 Position (dist * angle)';...
            'Stim1_lumi';...
            'Stim2_lumi';...
            'BG_lumi';...
            'Stim_Color';...
            'Stim1_Duration(sec)';...
            'Stim2_Duration(sec)';...
            'Corrected Stim1 ON(sec)';...
            'Corrected Stim1 OFF(sec)'
            };
    case {'Looming'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Position';...
            'Speed(deg/s)';...
            'Max Size(deg)';...
            'Stim_lumi';...
            'BG_lumi';...
            'Stim_Color';...
            'Duration(sec)';...
            'Corrected Stim ON(sec)';...
            'Corrected Stim OFF(sec)'
            };
        
        if n <= r.prestim
            pre_val={'NA';'NA';'NA';'NA';'NA';'NA';'NA';'NA';'NA'};
            values = [values; pre_val];
        else
            s1n = p{1,n}.stim1;
            specific_val={[pos,num2str(s1n.center_position)];...
                s1n.LoomingSpd_deg_s; s1n.LoomingMaxSize_deg;...
                s1n.lumi; s.bgcol; s1n.color(1);...
                s1n.Off_time - s1n.On_time;...
                ParamsSave{1,n}.stim1.corON;...
                ParamsSave{1,n}.stim1.corOFF;...
                };
            values = [values; specific_val];
        end
        
        
    case {'Sin', 'Rect', 'Gabor'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size(deg)';...
            'Position';...
            'Spatial Freq(cycle/deg)';...
            'Temporal Freq(Hz)';...
            'Angle (deg)';
            'Stim_lumi';...
            'BG_lumi';...
            'Stim_Color';...
            'Duration(sec)';...
            'Corrected Stim ON(sec)';...
            'Corrected Stim OFF(sec)'
            };
        if n <= r.prestim
            pre_val={'NA';'NA';'NA';'NA';'NA';'NA';'NA';'NA';'NA';'NA';'NA'};
            values = [values; pre_val];
        else
            s1n = p{1,n}.stim1;
            specific_val={s1n.size_deg;...
                [pos,num2str(s1n.center_position)];...
                s1n.gratingSF_cyc_deg; s1n.gratingSpd_Hz; s1n.gratingAngle_deg;...
                s1n.lumi; num2str(s.bgcol); s1n.color(1);...
                s1n.Off_time - s1n.On_time;...
                ParamsSave{1,n}.stim1.corON;...
                ParamsSave{1,n}.stim1.corOFF;...
                };
            values = [values; specific_val];
        end
          
    case {'Images'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size(deg)';...
            'Position';...
            'Image#';...
            'BG_lumi';...
            'Duration(sec)';
            'Corrected Stim ON(sec)';...
            'Corrected Stim OFF(sec)'
            };
        if n <= r.prestim
            pre_val={'NA';'NA';'NA';'NA';'NA';'NA';'NA'};
            values = [values; pre_val];
        else
            s1n = p{1,n}.stim1;
            specific_val={s1n.size_deg;...
                [pos,num2str(s1n.center_position)];...
                s1n.Image_index; num2str(s.bgcol);...
                s1n.Off_time - s1n.On_time;...
                ParamsSave{1,n}.stim1.corON;...
                ParamsSave{1,n}.stim1.corOFF;...
                };
            values = [values; specific_val];
        end
    case {'Mosaic'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Dist(deg)';...
            'Div';...
            'Center Pos';...
            'Image#';...
            'BG_lumi';...
            'Duration(sec)';
            'Corrected Stim ON(sec)';...
            'Corrected Stim OFF(sec)'
            };
    case {'FineMap'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size(deg)';...
            'Position';...
            'Image#';...
            'BG_lumi';...
            'Duration(sec)';
            'Corrected Stim ON(sec)';...
            'Corrected Stim OFF(sec)'
            };
end
%{
rnames = {'Recording Time (ms)';...
    'Sampling Time (us)';...
    'PlotType';'Cycle#';...
    'StimON/OFF';...
    'Stim_Sz1(pix)';...
    'Stim_Sz2(pix)';...
    'Monitor Divide';...
    'Stim1_Pos';...
    'Stim2_Pos(dist&ang)';...
    'Stim_Pattern';...
    'Duration';...
    'Stim_Color';...
    'BG_Color';...
    'Direction';...
    'Shift_Angle';...
    'Grating_Freq';...
    'Shift_Speed';...
    'Dealy TTL2(sec)';...
    'Delay PTBon (sec)';...
    'Correct Delay PTBon';...
    'Elapsed PTBon (sec)';...
    'Images_#';};
%}
end
