function Open_Params_Table(hfig_handle, p, r, s)
global hfig
hfig.params_table = figure('Position', [850, 20, 360, 600], 'Name', 'Parameters',...
    'NumberTitle', 'off', 'Menubar', 'none', 'Resize', 'off',...
    'DeleteFcn', {@Close_subwindow, hfig_handle});

[rnames, values]= Get_stim_param_values(p, r, s);

uiT = uitable(hfig.params_table, 'Data', values,...
    'ColumnName','Value', 'ColumnWidth',{100},'RowName',rnames,...
    'position',[5 300 350 540],'ColumnFormat',{'char'});
%Set table width and height
uiT.Position(2) =  600 - uiT.Extent(4)-5;
uiT.Position(3) =  uiT.Extent(3);
uiT.Position(4) =  uiT.Extent(4);

end

%%
function [rnames, values] = Get_stim_param_values(p, r, s)
global n
values = {(r.rect); (r.sampf); s.pattern; (n)};
pos = [num2str(s.divnum),'x',num2str(s.divnum),'=>'];
switch s.pattern
    case {'Uni', 'Size_rand'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Freq(Hz)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size(deg)';...
            'Position';...
            'Stim_lumi';...
            'BG_lumi';...
            'Stim_Color';...
            'Stim_Duration(sec)';...
            'Corrected Delay(sec)';
            };
        
        if n <= r.prestim
            pre_val={'NA';'NA';'NA';'NA';'NA';'NA';'NA'};
            values = [values; pre_val];
        else
            s1n = p{1,n}.stim1;
            specific_val={s1n.size_deg; [pos,num2str(s1n.center_position)];...
                s1n.lumi; num2str(s.bgcol); s1n.color(1);...
                s1n.Off_time - s1n.On_time; '0';
                };
            values = [values; specific_val];
        end
        
    case {'1P_Conc'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size(deg)';...
            'Center';...
            'Position (dist * angle)';...
            'Stim_lumi';...
            'BG_lumi';...
            'Stim_Color';...
            'Stim_Duration(sec)';...
            'Corrected Delay(sec)';
            };
    case {'2P_Conc'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size1(deg)';...
            'Size2(deg)';...
            'Stim1 Position';...
            'Stim2 Position (dist * angle)';...
            'Stim1_lumi';...
            'Stim2_lumi';...
            'BG_lumi';...
            'Stim_Color';...
            'Stim1_Duration(sec)';...
            'Stim2_Duration(sec)';...
            'Corrected Delay1(sec)';
            'Corrected Delay2(sec)';
            };
    case {'Looming'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size(deg)';...
            'Position';...
            'Speed(deg/s)';...
            'Max Size(deg)';...
            'Stim_lumi';...
            'BG_lumi';...
            'Stim_Color';...
            'Stim_Duration(sec)';...
            'Corrected Delay(sec)';
            };
    case {'Sin', 'Rect', 'Gabor'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size(deg)';...
            'Position';...
            'Spatial Freq(cycle/deg)';...
            'Temporal Freq(Hz)';...
            'Angle (deg)';
            'Stim_lumi';...
            'BG_lumi';...
            'Stim_Color';...
            'Stim_Duration(sec)';...
            'Corrected Delay(sec)';
            };
    case {'Images'}
        rnames = {
            'Recording Time(ms)';...
            'Sampling Time(us)';...
            'Stim_Pattern';...
            'Trial#';...
            'Size(deg)';...
            'Position';...
            'Image#';...
            'BG_lumi';...
            'Stim_Duration(sec)';...
            'Corrected Delay(sec)';
            };
    case {'Mosaic'}
    case {'FineMap'}
end
%{
rnames = {'Recording Time (ms)';...
    'Sampling Time (us)';...
    'PlotType';'Cycle#';...
    'StimON/OFF';...
    'Stim_Sz1(pix)';...
    'Stim_Sz2(pix)';...
    'Monitor Divide';...
    'Stim1_Pos';...
    'Stim2_Pos(dist&ang)';...
    'Stim_Pattern';...
    'Stim_Duration';...
    'Stim_Color';...
    'BG_Color';...
    'Direction';...
    'Shift_Angle';...
    'Grating_Freq';...
    'Shift_Speed';...
    'Dealy TTL2(sec)';...
    'Delay PTBon (sec)';...
    'Correct Delay PTBon';...
    'Elapsed PTBon (sec)';...
    'Images_#';};
%}
end
